title: Carlie Documentation (ACRV)
lang: en
description: Documentation and guides for Carlie, the mini-autonomous vehicle platform developed by the Australian Centre for Robotic Vision (ACRV)

#remote_theme: jekyll-rtd-theme

# baseurl: "/Carlie_Documentation"
# url: "localhost:4000"

nav_version: true
edit: true
addons_branch: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed

plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
